### ISSUE TITLE
Have you ever tried https://tfhub.dev/google/tfjs-model/movenet/multipose/lightning/1 ?

### ISSUE THREAD

**Issue by liamsun2019** [Kazuhito00/MoveNet-Python-Example#4]
Hi, have you ever tried the model:
https://tfhub.dev/google/tfjs-model/movenet/multipose/lightning/1

which is a model  in tfjs representation. I convert it to an onnx model using:
python3.6 -m tf2onnx.convert --opset 11 --tfjs model.json --output test.onnx   --inputs-as-nchw input

where model.json is one of the extracted files from tfjs-model_movenet_multipose_lightning_1.tar.gz

Then I apply this onnx model to multipose detection, but the inference results are very bad. I compare the results with that of https://tfhub.dev/google/movenet/multipose/lightning/1 and they are pretty different. But I cannot find out the possible reason. Any suggestions? Thanks.

**Comment by liamsun2019** [comment]
In addition, I also converted the tf version to onnx:
python3.6 -m tf2onnx.convert --saved-model movenet_multipose_lightning_1 --output model.onnx --opset=11 --inputs-as-nchw input
where movenet_multipose_lightning_1 is the path to which movenet_multipose_lightning_1.tar.gz is uncompressed containing the saved pb model.

The onnx model also performs bad. Looks very strange.

**Comment by Kazuhito00** [comment]
This repository does not support tfjs.

Also, even if I convert the tf file to ONNX(NCHW), the accuracy does not seem to deteriorate.
You should check if the inference process is error-free.

Blue：tf　Red：ONNX(NCHW)
<img src="https://user-images.githubusercontent.com/37477845/146796235-9d0977de-787a-4597-af37-2e4cc7eb07f7.jpg" loading="lazy" width="400px">　<img src="https://user-images.githubusercontent.com/37477845/146796258-f111a6ba-fb49-4098-b172-11d4387e8efe.jpg" loading="lazy" width="400px">

**Comment by liamsun2019** [comment]
Thanks for your feedback. In fact, when I convert the tfjs to onnx using tf2onnx.convert with option '--inputs-as-nchw', the generated onnx performs badly(I adjust the input shape to nchw accordingly in my inference code). In contrast, if '--inputs-as-nchw' is not applied, i.e, the input remains nhwc, the onnx performs well(I feed the model with shape of nhwc accordingly). I am curious why this happen.

**Comment by Kazuhito00** [comment]
This repository does not support tfjs.
